services:
  postgres:
    image: postgres:17
    container_name: postgres-sql-book-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - book-network
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev:latest
    container_name: mail-dev-book-network
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - book-network

networks:
  book-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
